name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --ulimit nofile=65536:65536 --progress=plain --no-cache -t jellyfin-tizen-build .
      
    - name: Make output dir
      run: mkdir -p output
      
    - name: Touch test file
      run: touch output/.test || sudo chown $USER:$USER output

    - name: Save image
      run: docker save -o "$(pwd)/output/jellyfin-tizen-build.tar" jellyfin-tizen-build

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: Jellyfin.wgt
        path: output/jellyfin-tizen-build.tar
